// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLo8OiJf9EKNJsu_Z5eTpV41Kem5zoU_g',
    appId: '1:1020539411619:web:e15e1d283cfe3d6ce73316',
    messagingSenderId: '1020539411619',
    projectId: 'desafio-4-9035a',
    authDomain: 'desafio-4-9035a.firebaseapp.com',
    storageBucket: 'desafio-4-9035a.appspot.com',
    measurementId: 'G-SWH5FH4Y3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKO_FkAxIlfhF_02lFzLoOvl9FkcyYTM',
    appId: '1:1020539411619:android:8233ca5a42ab24ebe73316',
    messagingSenderId: '1020539411619',
    projectId: 'desafio-4-9035a',
    storageBucket: 'desafio-4-9035a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdE3WXrudrCxzi1uHiTi1aiGVF8KM10TM',
    appId: '1:1020539411619:ios:1b90c440a3ca3a79e73316',
    messagingSenderId: '1020539411619',
    projectId: 'desafio-4-9035a',
    storageBucket: 'desafio-4-9035a.appspot.com',
    iosClientId: '1020539411619-nehgdt20e0vl852c3gkaq0ft8ajo14f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdE3WXrudrCxzi1uHiTi1aiGVF8KM10TM',
    appId: '1:1020539411619:ios:1b90c440a3ca3a79e73316',
    messagingSenderId: '1020539411619',
    projectId: 'desafio-4-9035a',
    storageBucket: 'desafio-4-9035a.appspot.com',
    iosClientId: '1020539411619-nehgdt20e0vl852c3gkaq0ft8ajo14f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
